# Generated by Django 3.2.7 on 2022-03-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20220303_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='PhoneNumber',
            field=models.IntegerField(default=0),
        ),
    ]
